import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.scss'
import { cn } from '@/lib/utils'

const montserrat = Montserrat({
	subsets: ['cyrillic'],
	variable: '--font-base',
})

export const metadata: Metadata = {
	title: 'Name',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${montserrat.className}`}>
				<div className={cn('relative min-h-full flex flex-col z-1')} >
					{children}
				</div>
			</body>
		</html>
	)
}
